export const gameList = [
  {
    type: "fishing",
    url: "/games/fishing/treasureking/",
    param: "useIFrame=true",
    name: "Treasure King",
    prefix: "treasureking",
    tighter: true,
  },
  {
    type: "slot",
    url: "/games/slot/witchlove/",
    param: "hidefps=true&useIFrame=true&hideTxID=true",
    name: "Witch Love",
    prefix: "witch",
    gamelink:
      "https://d29juml4m9n88c.cloudfront.net/games/slot/witchlove/?lang=zh-chs&curr=usd&hidefps=true&useIFrame=true&hideTxID=true",
  },
  {
    type: "slot",
    url: "/games/slot/adventureofsinbad/",
    param: "hidefps=true&useIFrame=true&hideTxID=true",
    name: "Adventure Of Sinbad",
    prefix: "sinbad",
  },
  {
    type: "slot",
    url: "/games/slot/nekomaid/",
    param: "hidefps=true&useIFrame=true&hideTxID=true",
    name: "Neko Maid",
    prefix: "maid",
    tighter: true,
  },
  {
    type: "spin",
    url: "/games/sicbo/sicbovideo/",
    param: "useIFrame=true&hideTxID=true",
    name: "Sicbo Spin",
    prefix: "sicbo",
    tighter: true,
  },
  {
    type: "spin",
    url: "/games/sicbo/xocdiavideo/",
    param: "useIFrame=true&hideTxID=true",
    name: "Xoc Dia Spin",
    prefix: "xocdia",
    tighter: true,
  },
  {
    type: "spin",
    url: "/games/sicbo/hooheyhowvideo/",
    param: "useIFrame=true&hideTxID=true",
    name: "Fish Prawn Crab Spin",
    prefix: "fishprawncrab",
    tighter: true,
  },
  {
    type: "blockchain",
    url: "/games/crash/blastxp/",
    param: "useIFrame=true&hideTxID=true",
    name: "Blast X",
    prefix: "blastx",
    tighter: true,
  },
  {
    type: "blockchain",
    url: "/games/crash/dicep/",
    param: "useIFrame=true&hideTxID=true",
    name: "Dice",
    prefix: "dice",
    tighter: true,
  },
  {
    type: "blockchain",
    url: "/games/crash/hilop/",
    param: "useIFrame=true&hideTxID=true",
    name: "HiLo",
    prefix: "hilo",
    tighter: true,
  },
  {
    type: "blockchain",
    url: "/games/crash/plinkop/",
    param: "useIFrame=true&hideTxID=true",
    name: "Plinko",
    prefix: "plinko",
    tighter: true,
  },
  {
    type: "blockchain",
    url: "/games/crash/wheelp/",
    param: "useIFrame=true&hideTxID=true",
    name: "Wheel",
    prefix: "wheel",
    tighter: true,
  },
];
